### ISSUE TITLE
add a cpp program for fibonacci series upto 20 numbers and replace multiples of 5 and prime numebrs with zero

### ISSUE THREAD

**Issue by diwakar1998** [diwakar1998/MyHackToberFest2021#1]

**Comment by dinesh-kumar-kangani** [comment]
I would like to contribute

**Comment by dinesh-kumar-kangani** [comment]
I am taking the first number from 1 and also for 100th value, the value's size may cross the range of int

**Comment by diwakar1998** [comment]
https://hacktoberfest.digitalocean.com/profile check your pr count here

**Comment by Blankita21** [comment]
Hi, I would like to work on this, kindly assign me this issue.

**Comment by diwakar1998** [comment]
> Hi, I would like to work on this, kindly assign me this issue.

done please go ahead

**Comment by Blankita21** [comment]
Just to make sure, I have to write a program to print the fibonacci number from 1-20 and replace the answers of prime numbers and multiples of 5 with 0 right?

**Comment by surajwakka** [comment]
I would like to Contribute

**Comment by dinesh-kumar-kangani** [comment]
> Just to make sure, I have to write a program to print the fibonacci number from 1-20 and replace the answers of prime numbers and multiples of 5 with 0 right?

@Blankita21 you are right...

**Comment by Divya333** [comment]
Hey please assign this to me i will do it

**Comment by Blankita21** [comment]
> > Just to make sure, I have to write a program to print the fibonacci number from 1-20 and replace the answers of prime numbers and multiples of 5 with 0 right?
> 
> @Blankita21 you are right...

I have uploaded the solution , kindly merge it.

**Comment by Blankita21** [comment]
> > Just to make sure, I have to write a program to print the fibonacci number from 1-20 and replace the answers of prime numbers and multiples of 5 with 0 right?
> 
> @Blankita21 you are right...

I have uploaded the solution , kindly merge #6 .

**Comment by diwakar1998** [comment]
...
